### ISSUE TITLE
Using this prebuilt package with nodejs and websockets fails for me

### ISSUE THREAD

**Issue by gajanak** [crossbario/autobahn-js-built#6]
Using the prebuild package of autobahn on nodejs, to implement a WAMP Client over Websocket connection, it gives some Problems with Websockets.

The code use `var WebSocket = require('ws');` on Connectto get a WebSocket Constructor. This fails. I don't know exactly why, but i think, it's the used packaging tool. As an Workaround i adding a patch. 
(see attachment), to allow injecting Websocket package.
```
var autobahn = require('autobahn-js-built/autobahn.js')
global.WebSocket = require('ws')
...
new autobahn.Connection

```

This way, I can use the js for Browser and nodejs.

But I don't like this solution.

But perhaps its help some else, or someone can give me a hint for a better solution.
(Perhaps ,giving reference to ws in the connection/transport parameters ?)

The second diff-part, is for accepting self-signed certificates with WebSockets.
(rejectUnauthorized). I don't found the right way to give this option to autobahn, yet.

[autobahn-js-built.patch.txt](https://github.com/crossbario/autobahn-js-built/files/1144297/autobahn-js-built.patch.txt)

**Comment by oberstet** [comment]
The version in this repo is exclusively for browser use - for Node, please use https://www.npmjs.com/package/autobahn

**Comment by oberstet** [comment]
also, this repo isn't for development, but only for distribution - I will remove the issue tracker ..
